### ISSUE TITLE
Chương trình compile thất bại tại hàm inputData()

### ISSUE THREAD

**Issue by duotien** [HoangHuyH/TicTacToe#1]
```
inputSuccess = True;
```

Trong C++, từ khóa đúng của loại bool là `true`, `false`
Nhớ sửa lại các giá trị cho đúng

**Comment by HoangHuyH** [comment]
cái này ông viết chứ ai viết :))

**Comment by duotien** [comment]
Thói quen bên Python lol, mà copy không sửa code nè :))

**Comment by HoangHuyH** [comment]
bình tĩnh mai thì xong fix tiếp =="
